# Generated by Django 5.1.5 on 2025-02-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_subject_ticket_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='subject',
        ),
    ]
