# Generated by Django 5.1.6 on 2025-02-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_ticket_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketredirect',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='ticketredirect',
            name='redirected_at',
        ),
    ]
