# Generated by Django 5.1.5 on 2025-01-29 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ticket_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='departments',
        ),
        migrations.AddField(
            model_name='officer',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.department'),
            preserve_default=False,
        ),
    ]
