# Generated by Django 5.1.5 on 2025-02-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_ticketredirect_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
