# Generated by Django 5.1.6 on 2025-03-13 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_officer_is_department_head_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Open', 'In Progress', 'Awaiting Student', 'Closed'])), name='valid_ticket_status'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['Low', 'Medium', 'High']), ('priority__isnull', True), _connector='OR'), name='valid_ticket_priority'),
        ),
    ]
